### PR TITLE
Update composer.json with PHP version 8.2

### PR DESCRIPTION
**Pull request by Shiriaev**
On the basis of this issue https://github.com/buckaroo-it/Magento2_Hyva_Checkout/issues/21 I updated PHP version in composer.json

### CODE REVIEW

**Comment by elzekool** [comment]
@Shiriaev ,

With the current PR you do not allow installation with 8.1 anymore, would suggest:
"require": "~8.1.0|~8.2.0"

See also https://semver.madewithlove.com/?package=php&constraint=~8.1.0%7C~8.2.0

**Comment by Shiriaev** [comment]
Hello @elzekool , thanks for the good suggestion, the PR was updated.

**Review by LucianTuriacArnia — CHANGES_REQUESTED** [review]

**Comment by elzekool** [comment]
@LucianTuriacArnia With ">= 8.1" as a constraint you are also indicating compatibility with any future PHP 8.x versions, is that indeed the intention?

**Comment by LucianTuriacArnia** [comment]
Yes, our approach is to ensure compatibility with the latest PHP versions, and we regularly conduct tests and make necessary updates. Therefore, specifying ">= 8.1" in our constraints is intentional to support all future PHP 8.x releases.

**Review by LucianTuriacArnia — APPROVED** [review]

**Comment by Shiriaev** [comment]
@LucianTuriacArnia can you please add version tag for this PR? Thanks!

**Comment by Shiriaev** [comment]
Hello @LucianTuriacArnia ! Thanks for tagging. However, the package still not updated in packagist, I see only old version there. Could you please trigger packagist update manually, or enable hook for packagist? Thanks in advance!

**Comment by Buckaroo-Rene** [comment]
Goodmorning @Shiriaev ,
Thanks for the heads-up, it is updated now on packagist.

Best Regards,
René

**Pull request merged**
